# Generated by Django 5.2.16 on 2026-07-10 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={"ordering": ["-id"], "verbose_name": "Token", "verbose_name_plural": "Tokens"},
        ),
    ]
